name: "Notify Microsoft Teams"
description: "Send notifications to Microsoft Teams using Adaptive Cards."
author: "nerazshakya"
branding:
  icon: "message-circle"
  color: "blue"

inputs:
  webhook_url:
    description: "Microsoft Teams Incoming Webhook URL"
    required: true
  title:
    description: "Notification title"
    required: false
    default: "GitHub Action Notification"
  message:
    description: "Notification message"
    required: true
  status:
    description: "Build status (Success, Failure, Skipped, Cancelled, Unknown)"
    required: false
    default: "Unknown"

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_WEBHOOK_URL: ${{ inputs.webhook_url }}
    INPUT_TITLE: ${{ inputs.title }}
    INPUT_MESSAGE: ${{ inputs.message }}
    INPUT_STATUS: ${{ inputs.status }}