name: 'Notify Microsoft Teams'
description: 'Send GitHub Actions notifications to a Microsoft Teams channel using Adaptive Cards.'
author: 'nerazshakya'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  webhook_url:
    description: 'Microsoft Teams Incoming Webhook URL'
    required: true
  title:
    description: 'Title of the notification'
    required: false
    default: 'GitHub Action Notification'
  message:
    description: 'Main message of the notification'
    required: true
  status:
    description: 'Build status (Success, Failure, Skipped, Cancelled, Unknown)'
    required: false
    default: 'Unknown'
  theme_color:
    description: 'Theme color for MessageCard (Not used in Adaptive Card, kept for backward compatibility)'
    required: false
    default: '0076D7'
  repository:
    description: 'GitHub Repository Name'
    required: false
  ref_name:
    description: 'Git Branch Name'
    required: false
  commit_sha:
    description: 'Git Commit SHA'
    required: false
  actor:
    description: 'GitHub Actor who triggered the workflow'
    required: false
  event_name:
    description: 'GitHub Event Name'
    required: false

outputs:
  result:
    description: 'Result of the notification request'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_WEBHOOK_URL: ${{ inputs.webhook_url }}
    INPUT_TITLE: ${{ inputs.title }}
    INPUT_MESSAGE: ${{ inputs.message }}
    INPUT_STATUS: ${{ inputs.status }}
    INPUT_THEME_COLOR: ${{ inputs.theme_color }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    GITHUB_REF_NAME: ${{ inputs.ref_name }}
    GITHUB_SHA: ${{ inputs.commit_sha }}
    GITHUB_ACTOR: ${{ inputs.actor }}
    GITHUB_EVENT_NAME: ${{ inputs.event_name }}
