name: 'Notify Microsoft Teams'
description: 'Send GitHub Actions notifications to Microsoft Teams using Adaptive Cards'
author: 'nerazshakya'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  webhook_url:
    description: 'Microsoft Teams Incoming Webhook URL'
    required: true
  title:
    description: 'Notification Title'
    required: false
    default: 'GitHub Action Notification'
  message:
    description: 'Notification Message'
    required: true
  status:
    description: 'Build Status (Success, Failure, Skipped, Cancelled, Unknown)'
    required: false
    default: 'Unknown'

runs:
  using: 'docker'
  image: 'Dockerfile'
