name: 'Notify Microsoft Teams'
description: 'Send GitHub Actions notifications to Microsoft Teams using Adaptive Cards'
author: 'nerazshakya'
branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  webhook_url:
    description: 'Microsoft Teams Incoming Webhook URL'
    required: true
  title:
    description: 'Notification Title'
    required: false
    default: 'GitHub Action Notification'
  status:
    description: 'Status (Success, Failure, Skipped, Cancelled, Unknown)'
    required: false
    default: 'Unknown'
  files_changed:
    description: 'List of changed files'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Python Dependencies
      shell: bash
      run: pip install -r "${{ env.GITHUB_ACTION_PATH }}/requirements.txt"

    - name: Run Notification Script
      shell: bash
      run: python "${{ env.GITHUB_ACTION_PATH }}/notify.py"
