name: Notify Teams on Build Status
on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Send Notification to Teams
        uses: nerazshakya/notify-msteams@main
        with:
          webhook_url: 'https://your-teams-webhook-url'
          title: 'Build Notification'
          message: 'The latest build has completed successfully!'
          status: 'Success'
