name: Reusable Teams Notification Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        description: "Message to send to Teams"
      card_title:
        required: false
        type: string
        default: "GitHub Actions Notification"
      card_type:
        required: false
        type: string
        default: "basic"
        description: "Type of card template to use (basic, detailed, error)"
    secrets:
      TEAMS_WEBHOOK_URL:
        required: true
      PAT_TOKEN:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Send Teams notification
        run: |
          python -m src.teams_notification.client \
            --title "${{ inputs.card_title }}" \
            --message "${{ inputs.message }}" \
            --type "${{ inputs.card_type }}"
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
